actionlint = "github.com/rhysd/actionlint"
ast-grep = "github.com/ast-grep/ast-grep"
atuin = "github.com/atuinsh/atuin" # *
bat = "github.com/sharkdp/bat"
biome = "github.com/biomejs/biome"
btm = "github.com/ClementTsang/bottom"
bun = "github.com/oven-sh/bun"
caddy = "github.com/caddyserver/caddy"
chezmoi = "github.com/twpayne/chezmoi"
claude = "github.com/anthropics/claude-code"
codegraph = "github.com/colbymchenry/codegraph"
codex = "github.com/openai/codex"
delta = "github.com/dandavison/delta" # *
deno = "github.com/denoland/deno"
difftastic = "github.com/Wilfred/difftastic"
dprint = "github.com/dprint/dprint"
dua = "github.com/Byron/dua-cli"
dust = "github.com/bootandy/dust"
fd = "github.com/sharkdp/fd"
fzf = "github.com/junegunn/fzf"
git-lfs = "github.com/git-lfs/git-lfs"
golangci-lint = "github.com/golangci/golangci-lint"
goreleaser = "github.com/goreleaser/goreleaser"
grpcurl = "github.com/fullstorydev/grpcurl" # *
helix = "github.com/helix-editor/helix" # *
hyperfine = "github.com/sharkdp/hyperfine" # *
jq = "github.com/jqlang/jq"
just = "github.com/casey/just"
k9s = "github.com/derailed/k9s"
lazydocker = "github.com/jesseduffield/lazydocker"
lazygit = "github.com/jesseduffield/lazygit"
"llama.cpp" = "github.com/ggml-org/llama.cpp"
lsd = "github.com/lsd-rs/lsd" # *
mdbook = "github.com/rust-lang/mdBook" # *
nerd-fonts = "github.com/ryanoasis/nerd-fonts"
nu = "github.com/nushell/nushell"
nvim = "github.com/neovim/neovim"
opencode = "github.com/anomalyco/opencode"
ouch = "github.com/ouch-org/ouch"
pnpm = "github.com/pnpm/pnpm"
procs = "github.com/dalance/procs" # *
psnwdl = "github.com/meop/PSNWDL"
pwsh = "github.com/PowerShell/PowerShell"
rclone = "github.com/rclone/rclone"
rg = "github.com/BurntSushi/ripgrep"
ruff = "github.com/astral-sh/ruff"
rv = "github.com/spinel-coop/rv"
scc = "github.com/boyter/scc"
sd = "github.com/chmln/sd" # *
starship = "github.com/starship/starship"
taplo = "github.com/tamasfe/taplo"
task = "github.com/go-task/task"
tealdeer = "github.com/dbrgn/tealdeer"
tree-sitter = "github.com/tree-sitter/tree-sitter"
uv = "github.com/astral-sh/uv"
vivid = "github.com/sharkdp/vivid" # *
watchexec = "github.com/watchexec/watchexec"
winenvedit = "github.com/meop/WinEnvEdit"
yay = "github.com/Jguer/yay"
yazi = "github.com/sxyazi/yazi"
yq = "github.com/mikefarah/yq"
zellij = "github.com/zellij-org/zellij" # *
zoxide = "github.com/ajeetdsouza/zoxide"
zstd = "github.com/facebook/zstd" # *

# * waiting for windows arm64 release
