actionlint = "github.com/rhysd/actionlint"
age = "github.com/FiloSottile/age"                  # https://github.com/FiloSottile/age/issues/733 *
ast-grep = "github.com/ast-grep/ast-grep"
atuin = "github.com/atuinsh/atuin"                  # https://github.com/atuinsh/atuin/issues/3056 *
bat = "github.com/sharkdp/bat"
biome = "github.com/biomejs/biome"
btm = "github.com/ClementTsang/bottom"
bun = "github.com/oven-sh/bun"
caddy = "github.com/caddyserver/caddy"
chezmoi = "github.com/twpayne/chezmoi"
claude = "github.com/anthropics/claude-code"
codegraph = "github.com/colbymchenry/codegraph"
codex = "github.com/openai/codex"
croc = "github.com/schollz/croc"
delta = "github.com/dandavison/delta"               # https://github.com/dandavison/delta/issues/2223 * ****
deno = "github.com/denoland/deno"
difftastic = "github.com/Wilfred/difftastic"
direnv = "github.com/direnv/direnv"
dive = "github.com/wagoodman/dive"
dprint = "github.com/dprint/dprint"
dua = "github.com/Byron/dua-cli"
duf = "github.com/muesli/duf"
dust = "github.com/bootandy/dust"
fastfetch = "github.com/fastfetch-cli/fastfetch"
fd = "github.com/sharkdp/fd"
fzf = "github.com/junegunn/fzf"
gdu = "github.com/dundee/gdu"                       # ? *
git-lfs = "github.com/git-lfs/git-lfs"
glow = "github.com/charmbracelet/glow"              # ? *
golangci-lint = "github.com/golangci/golangci-lint"
goreleaser = "github.com/goreleaser/goreleaser"
grpcurl = "github.com/fullstorydev/grpcurl"         # https://github.com/fullstorydev/grpcurl/issues/541 *
gum = "github.com/charmbracelet/gum"                # ? *
helix = "github.com/helix-editor/helix"             # https://github.com/helix-editor/helix/issues/10872 *
hexyl = "github.com/sharkdp/hexyl"                  # https://github.com/sharkdp/hexyl/pull/291 * ****
hurl = "github.com/Orange-OpenSource/hurl"          # ? *
hyperfine = "github.com/sharkdp/hyperfine"          # https://github.com/sharkdp/hyperfine/pull/922 * ****
jq = "github.com/jqlang/jq"
just = "github.com/casey/just"
k9s = "github.com/derailed/k9s"
lazydocker = "github.com/jesseduffield/lazydocker"
lazygit = "github.com/jesseduffield/lazygit"
"llama.cpp" = "github.com/ggml-org/llama.cpp"
lsd = "github.com/lsd-rs/lsd"                       # https://github.com/lsd-rs/lsd/pull/1236 *
mdbook = "github.com/rust-lang/mdBook"              # https://github.com/rust-lang/mdBook/pull/3193 * ***
mise = "github.com/jdx/mise"
nerd-fonts = "github.com/ryanoasis/nerd-fonts"
nu = "github.com/nushell/nushell"
nvim = "github.com/neovim/neovim"
opencode = "github.com/anomalyco/opencode"          # https://github.com/anomalyco/opencode/issues/45875 *
ouch = "github.com/ouch-org/ouch"
pastel = "github.com/sharkdp/pastel"                # https://github.com/sharkdp/pastel/pull/320 * ****
pnpm = "github.com/pnpm/pnpm"
procs = "github.com/dalance/procs"                  # https://github.com/dalance/procs/pull/961 *
psnwdl = "github.com/meop/PSNWDL"
pwsh = "github.com/PowerShell/PowerShell"
qsv = "github.com/dathere/qsv"                      # https://github.com/dathere/qsv/issues/2945 * ****
rclone = "github.com/rclone/rclone"
restic = "github.com/restic/restic"                 # https://github.com/restic/restic/issues/3596 *
rg = "github.com/BurntSushi/ripgrep"
ruff = "github.com/astral-sh/ruff"
rv = "github.com/spinel-coop/rv"
scc = "github.com/boyter/scc"
sd = "github.com/chmln/sd"                          # https://github.com/chmln/sd/issues/329 * ***
shfmt = "github.com/mvdan/sh"                       # https://github.com/mvdan/sh/issues/1077 *
sops = "github.com/getsops/sops"
starship = "github.com/starship/starship"
stern = "github.com/stern/stern"
taplo = "github.com/tamasfe/taplo"
task = "github.com/go-task/task"
tealdeer = "github.com/dbrgn/tealdeer"
tree-sitter = "github.com/tree-sitter/tree-sitter"
typos = "github.com/crate-ci/typos"                 # https://github.com/crate-ci/typos/pull/1602 *
uv = "github.com/astral-sh/uv"
vhs = "github.com/charmbracelet/vhs"                # ? *
vivid = "github.com/sharkdp/vivid"                  # https://github.com/sharkdp/vivid/pull/228 * ****
watchexec = "github.com/watchexec/watchexec"
winenvedit = "github.com/meop/WinEnvEdit"
xan = "github.com/medialab/xan"                     # ? * ****
yay = "github.com/Jguer/yay"
yazi = "github.com/sxyazi/yazi"
yq = "github.com/mikefarah/yq"
zellij = "github.com/zellij-org/zellij"             # https://github.com/zellij-org/zellij/pull/5090 *
zoxide = "github.com/ajeetdsouza/zoxide"

# ? fork investigation not yet complete
# * missing Windows ARM64 release
# ** missing macOS ARM64 release
# *** missing Linux ARM64 GNU release
# **** missing Linux ARM64 musl release
